=== Sauvegarde

=== Version Communautaire

Toutes les données sont stockés dans le répertoire `data/graph.db`.
Ainsi pour effectuer une sauvegarder des données, voici la marche à suivre :

* Eteindre le service Neo4j
* Sauvegarder le répertoire `data/graph.db`
* Redémarrer le service Neo4j

Comme vous pouvez le constater, la sauvegarde ne peut se faire uniquement si le service est éteint.

=== Version Entreprise

Dans sa version Entreprise, Neo4j dispose d'un outil de sauvegarde à chaud. Cet outil réalise deux actions :

* une copie du répertoire `data/graph.db` dans le répertoire spécifié
* une vérification de la cohérence des données

Voici la commande pour l'exécuter :

[source]
----
$>bin/neo4j-backup -to BACKUP_FOLDER -host NEO4J_IP -port BACKUP_PORT
----

Où : 

* **BACKUP_FOLDER** : est le répertoire vers lequel la sauvegarde sera réalisée. Si celui-ci contient déjà une précédent sauvegarde, l'outil va réaliser un delta avec la base (sauvegarde incrémentale).
* **NEO4J_HOST** : l'adresse IP de la machine Neo4j. Vu que l'utilitaire de savegarde est généralement sur la même machine que le serveur Neo4j, on utilise `localhost`
* **BACKUP_PORT** : Le port sur lequel Neo4j écoute les instructions de savegarde. Par défaut celui-ci est `6362`. Celui-ci peut être changé en modifiant la clef `online_backup_server` du fichier `conf.neo4j.properties`.

Même si la technique de sauvegarde peut être incrémetale, son livrable correspond toujours à l'intégralité de la base (ie. le répertoire `data/graph.db`).

Ce qui est généralement mis en place, c'est un cron qui toutes les heures vient faire la savegarde de manière incrémentale.
Puis une fois par jour, le répertoire est zippé et envoyé sur SAN/FTP/... pour une sauvegarde à long terme. 
